- name: Commit and Push
        if: steps.check.outputs.should_run == 'true'
        run: |
          git config --local user.email "tamannasinha2704@gmail.com"
          git config --local user.name "tamannasinha2704"
          git add _posts/
          # This line checks for changes; if none, it exits quietly instead of failing
          git diff-index --quiet HEAD || git commit -m "docs: automated technical research log [skip ci]"
          git push